# Generated by Django 5.2.6 on 2025-09-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_image', models.ImageField(upload_to='images/')),
                ('item_name', models.CharField(max_length=255)),
                ('item_description', models.CharField(max_length=255)),
                ('new_price', models.IntegerField()),
                ('old_price', models.IntegerField()),
                ('offer', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
            ],
        ),
    ]
