# Generated by Django 5.2.6 on 2025-10-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_image1', models.CharField(max_length=255)),
                ('item_image2', models.CharField(max_length=255)),
                ('item_image3', models.CharField(max_length=255)),
                ('item_image4', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('item_description', models.CharField(max_length=255)),
                ('new_price', models.IntegerField()),
                ('old_price', models.IntegerField()),
                ('offer', models.IntegerField()),
                ('category', models.CharField(choices=[('mens', 'Mens'), ('womens', 'Womens'), ('girls', 'Girls'), ('boys', 'Boys')], max_length=10)),
                ('item_quantity', models.IntegerField()),
                ('small_size', models.IntegerField()),
                ('medium_size', models.IntegerField()),
                ('large_size', models.IntegerField()),
                ('extralarge_size', models.IntegerField()),
            ],
        ),
    ]
