# Generated by Django 5.2.6 on 2025-11-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban_tees_app', '0002_alter_order_product_oreder_item_cart_oreder_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='user_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_text',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
