# Generated by Django 5.2.6 on 2025-10-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban_tees_app', '0002_remove_product_item_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone')),
                ('address', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=6)),
                ('role', models.CharField(max_length=255)),
                ('activity', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
    ]
