# Generated by Django 5.2.6 on 2025-11-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban_tees_app', '0003_cart_product_image_order_user_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
