# Generated by Django 5.2.6 on 2025-10-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urban_tees_app', '0003_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mail',
            new_name='email',
        ),
    ]
