# Generated by Django 5.2.6 on 2025-11-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban_tees_app', '0004_alter_cart_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_content',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_image',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_text',
        ),
        migrations.AddField(
            model_name='cart',
            name='user_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='user_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user_text',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
