# Generated by Django 5.2.6 on 2025-10-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban_tees_app', '0004_rename_mail_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
