# Generated by Django 5.2.6 on 2025-11-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban_tees_app', '0005_remove_order_user_content_remove_order_user_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user_image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
