# Generated by Django 5.2.6 on 2025-10-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban_tees_app', '0005_user_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], max_length=10),
        ),
    ]
