# Generated by Django 5.2.6 on 2025-11-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban_tees_app', '0006_alter_cart_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
