# Generated by Django 5.2.6 on 2025-11-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban_tees_app', '0007_alter_cart_user_image_alter_cart_user_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
