# Generated by Django 5.2.6 on 2025-11-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban_tees_app', '0008_cart_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_discount',
        ),
        migrations.AddField(
            model_name='cart',
            name='net_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_discount',
            field=models.IntegerField(null=True),
        ),
    ]
