# Generated by Django 5.2.6 on 2025-11-11 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban_tees_app', '0009_remove_order_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oreder_item',
            name='product',
        ),
        migrations.RemoveField(
            model_name='oreder_item',
            name='user',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='order_code',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_no',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_name',
        ),
        migrations.AddField(
            model_name='order',
            name='net_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='urban_tees_app.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extralarge', 'Extra Large')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Oreder_item',
        ),
    ]
