# Generated by Django 5.2.6 on 2025-11-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban_tees_app', '0010_remove_oreder_item_product_remove_oreder_item_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activity',
            field=models.CharField(choices=[('unblock', 'Unblock'), ('block', 'Block')], max_length=255),
        ),
    ]
